### ISSUE TITLE
Sound Configuration

### ISSUE THREAD

**Issue by piggz** [sailfish-on-dontbeevil/droid-config-pinephone#24]
Several issues exist with the sound configuration, mainly that the volume control doesnt work and the meego volume plugin causes a crash in PA

**Comment by neochapay** [comment]
I think partially fix this https://github.com/sailfish-on-dontbeevil/droid-config-pinephone/pull/31

**Comment by bjoern-tantau** [comment]
Not sure if this belongs here, but I wanted to document it somewhere.
I could finally hear and say something on the speaker on receiving a phone call by unmuting "DAC Mixer AIF2 DAC" (and slightly lowering DAC volume to about 24) and enabling capture of "AIF2 ADC Mixer ADC" with alsamixer.
I once even could get the earpiece to work, but I can't reproduce it now.

**Comment by DylanVanAssche** [comment]
@bjoern-tantau I tried your alsamixer command, but I haven't been able to get it to work though.

**Comment by piggz** [comment]
Vol control fixed
