### ISSUE TITLE
Ofono configuration

### ISSUE THREAD

**Issue by piggz** [sailfish-on-dontbeevil/droid-config-pinephone#26]

**Comment by Zurga** [comment]
Could we use the [setupscript](https://gitlab.com/postmarketOS/pmaports/-/blob/master/device/community/device-pine64-pinephone/setup-modem.sh) from PostmarketOS here?

**Comment by piggz** [comment]
My understanding is that script is only for the older kernels which dont use the new modem-power driver.  We are now using the 5.9 kernel with the modem-power driver which does all the initialisation, infact, ofono kinda works now, and ive both made and received calls.

**Comment by Zurga** [comment]
Okay, great! I don't have a lot of experience with Linux kernels and drivers. I will do some more background research next time I submit. SailfishOS looks really great btw.

**Comment by piggz** [comment]
This is resolved in the current build
