### ISSUE TITLE
Boot in eMMC issues. 

### ISSUE THREAD

**Issue by GNUuser** [sailfish-on-dontbeevil/droid-config-pinephone#36]
I installed Sailfish in eMMC, then it worked well for few time, but MAYBE  after  install many apps 
 and  later restart the phone, the pinephone the not  boot any more.
I still not have a JACK-SERIAL-CABLE to debugging the pinephone.
Just reporting ---

![pine-](https://user-images.githubusercontent.com/45316884/77715961-66a2dd00-6fb3-11ea-8e82-309f06dc9210.jpg)

**Comment by DylanVanAssche** [comment]
Can you please provide a more detailed explanation how this happened to be able to reproduce it?

**Comment by GNUuser** [comment]
I just installed many apps , then not boot  anymore, just turn the  white led on but screen is dark.  Is strange.

**Comment by GNUuser** [comment]
Sometimes I have noticed that it is difficult for the pinephone to recognize the previous brightness setting.

**Comment by piggz** [comment]
Maybe brightness, did you try holding a torch at the screen?

**Comment by GNUuser** [comment]
> Maybe brightness, did you try holding a torch at the screen?

No.

**Comment by GNUuser** [comment]
I not sure if u-boot is hang boot SF, or bad  brightness. So the easy way to fix this trouble is reflashing the os,  but that same issues could be  appear later

**Comment by GNUuser** [comment]
Just to add i guess that u-boot is hanging  boot  sf , because after turn on the pinephone I do not see any verbose on booting.

**Comment by GNUuser** [comment]
Also a friend have stranges issues in the pinephone , like black screen.  He sent me some videos.

**Comment by DylanVanAssche** [comment]
> Sometimes I have noticed that it is difficult for the pinephone to recognize the previous brightness setting.

Did you deactivate the auto brightness in Settings -> Display? And set the brightness to maximum?

**Comment by GNUuser** [comment]
> Did you deactivate the auto brightness in Settings -> Display? And set the brightness to maximum?
Yes i deactivate the auto brightness, then i configured the brightness manually to minimun to save batt.

**Comment by DylanVanAssche** [comment]
If you have a serial-USB adapter you can see what happens, otherwise it's just a guessing game unfortunately...

**Comment by GNUuser** [comment]
> If you have a serial-USB adapter you can see what happens, otherwise it's just a guessing game unfortunately...

Yeah. This Bug is true, one friend had same problems. I will order the serial-cable, cases, batteries next week.

**Comment by GNUuser** [comment]
When i turn on the pinephone it only turn on the led, neither the light of the background of the screen. Maybe one app that I installed it changed sensitively something in the system to not boot t infinitely.

**Comment by DylanVanAssche** [comment]
Probably U-boot ...

**Comment by GNUuser** [comment]
I reinstalled Sailfish in the eMMC, but before reflashing i did some test without serial-cable, so when i turning on the pinephone, the screen is dark always not verbose too but battery is running in background, Maybe this happen because i installed webcat togheter with webkit5.212-dev from Leszek repos, i guess webkit5.212 is broken the system, i do not want to install webkit5.212 again to maybe broken the system. Can you check  @DylanVanAssche webkit5.212-dev from Leszek??

**Comment by DylanVanAssche** [comment]
I don't see any issues with the Webkit from Leszek...

**Comment by GNUuser** [comment]
Thank you for testing. I was suspected it was by webkit5.212-wayland.

**Comment by GNUuser** [comment]
I will close this issue temporarily.
Thank you  @DylanVanAssche for you nice work to sf-pinephone.
