### ISSUE TITLE
USB OTG Support

### ISSUE THREAD

**Issue by piggz** [sailfish-on-dontbeevil/droid-config-pinephone#41]
With the 5.6 kernel, USB oTG is enabled and mostly works well.  RNDIS and MTP both work, but with rndis, the sailfish firewall doesnt allow connetions.  A workaround is to issue an iptables command to allow connections.

**Comment by piggz** [comment]
I have fixed this locally by changin connman and usb-moded configs, but looking for a proper solution.

**Comment by DylanVanAssche** [comment]
@piggz Is fixed now I guess?

**Comment by GNUuser** [comment]
USB-OTG support, you mean  USB-DataRole.?? @piggz @DylanVanAssche

**Comment by piggz** [comment]
Yes ... but probably should try OTG too!

**Comment by GNUuser** [comment]
@piggz I'm thinking if you not having a pinephone rev1.2 could slow down problems in porting sailfish well for the pinephone.?? If not to buy one for you.
