### ISSUE TITLE
pinephone-v1.1 not boot on new (1/5/20) img.

### ISSUE THREAD

**Issue by GNUuser** [sailfish-on-dontbeevil/droid-config-pinephone#44]
carlosgonz-GNU:~/Descargas/flash-it-0.3.1$ ./flash-it.sh
Sailfish OS Pine64 device flasher V0.3.1
======================================

Which image do you want to flash?
1) PinePhone 1.0 (Development) device  3) PineTab device
2) PinePhone 1.1 (Brave Heart) device  4) Dont Be Evil devkit
#? 2
Downloading images...
u-boot.zip          100%[===================>] 241.46K   370KB/s    en 0.7s    
pinephone-1.1-rootfs.zip                                    100%[========================================================================================================================================>] 432.96M  6.75MB/s    en 63s     
Which SD card do you want to flash?
NAME                      MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                         8:0    0 447.1G  0 disk  
├─sda1                      8:1    0   731M  0 part  /boot
└─sda5                      8:5    0 446.4G  0 part  
  └─sda5_crypt            253:0    0 446.4G  0 crypt 
    ├─trisquel--vg-root   253:1    0 445.4G  0 lvm   /
    └─trisquel--vg-swap_1 253:2    0   976M  0 lvm   [SWAP]
sdb                         8:16   1  14.7G  0 disk  
sr0                        11:0    1  1024M  0 rom   
nvme0n1                   259:0    0   477G  0 disk  
└─nvme0n1p1               259:1    0   477G  0 part  
raw
Device node (/dev/sdX): /dev/sdb
Flashing image to: /dev/sdb
WARNING: All data will be erased! You have been warned!
Some commands require root permissions, you might be asked to enter your sudo password.
Creating EXT4 file system...
Unmounting /dev/sdb
[sudo] contraseña para carlosgonz: 
umount: /dev/sdb: no montado.
mke2fs 1.44.1 (24-Mar-2018)
Se está creando un sistema de ficheros con 242688 bloques de 1k y 60720 nodos-i
UUID del sistema de ficheros: 9d63ba0a-12b7-45a8-8fb3-cf3122884d76
Respaldo del superbloque guardado en los bloques: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185

Reservando las tablas de grupo: hecho                            
Escribiendo las tablas de nodos-i: hecho                            
Creando el fichero de transacciones (4096 bloques): hecho
Escribiendo superbloques y la información contable del sistema de archivos: hecho

mke2fs 1.44.1 (24-Mar-2018)
Se está creando un sistema de ficheros con 3787264 bloques de 4k y 948416 nodos-i
UUID del sistema de ficheros: 912823f1-165e-4ced-912e-560d511ef661
Respaldo del superbloque guardado en los bloques: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Reservando las tablas de grupo: hecho                            
Escribiendo las tablas de nodos-i: hecho                            
Creando el fichero de transacciones (16384 bloques): hecho
Escribiendo superbloques y la información contable del sistema de archivos: hecho  

Flashing U-boot...
Archive:  u-boot.zip
  inflating: u-boot-bootloader/devkit/boot.scr  
  inflating: u-boot-bootloader/pinephone-1.0/boot.scr  
  inflating: u-boot-bootloader/pinephone-1.1/boot.scr  
  inflating: u-boot-bootloader/pinetab/boot.scr  
  inflating: u-boot-bootloader/u-boot/u-boot-sunxi-with-spl.bin  
60+1 registros leídos
60+1 registros escritos
494864 bytes (495 kB, 483 KiB) copied, 0.11773 s, 4.2 MB/s
Flashing rootFS...
Archive:  pinephone-1.1-rootfs.zip
  inflating: pinephone-1.1/sfe-pinephone-1.1-3.3.0.16-devel-20200501/Jolla-3.3.0.16-pinephone-1.1-armv7hl.ks  
  inflating: pinephone-1.1/sfe-pinephone-1.1-3.3.0.16-devel-20200501/Jolla-3.3.0.16-pinephone-1.1-armv7hl.packages  
  inflating: pinephone-1.1/sfe-pinephone-1.1-3.3.0.16-devel-20200501/Jolla-3.3.0.16-pinephone-1.1-armv7hl.urls  
  inflating: pinephone-1.1/sfe-pinephone-1.1-3.3.0.16-devel-20200501/sfe-pinephone-1.1-3.3.0.16-devel-20200501.tar.bz2  
pinephone-1.1/sfe-pinephone-1.1-3.3.0.16-devel-20200501/sfe-pinephone-1.1-3.3.0.16-devel-20200501.tar.bz2
Copying kernel to boot partition...
cp: no se puede efectuar `stat' sobre './data/boot/*': No existe el archivo o el directorio
Cleaning up!
Unmounting /dev/sdb
umount: /dev/sdb: no montado.
Unmounting /dev/sdb1
Unmounting /dev/sdb2
Flashing /dev/sdb OK!
You may now remove the SD card and insert it in your Pine64 device!

**Comment by GNUuser** [comment]
@DylanVanAssche Do you have a Pinephone v1.1? If yes , I will STOP opening new buggies.

**Comment by DylanVanAssche** [comment]
There are some issues with upgrading to Sailfish OS 3.3.0. We're currently looking into it :)
If have a PinePhone 1.0 which has the same issues as 1.1.

If the images are fixed, I will let you know :)

**Comment by DylanVanAssche** [comment]
Is this fixed now? @GNUuser

**Comment by GNUuser** [comment]
Yes it booting well. Thank you @DylanVanAssche .
