### ISSUE TITLE
double touch to Wake up the screen, seems not work after remove Vconn chips

### ISSUE THREAD

**Issue by GNUuser** [sailfish-on-dontbeevil/droid-config-pinephone#48]
MCE double tap no work after extract cc chipsets, PinePhone BH, not tested on PP CE.

**Comment by DylanVanAssche** [comment]
Unfortunately, I haven't done this 'fix', but others did :)

@piggz ?

**Comment by GNUuser** [comment]
> Unfortunately, I haven't done this 'fix', but others did :)
> 
> @piggz ?

The other that you did is already merged ??
What happen with the Sailfish Browser why not working??
PinePhone need too urgently newer CRUST because the battery is draining i lot. @piggz @neochapay @DylanVanAssche :  )

**Comment by piggz** [comment]
Sailfish browser if s broken for mesa based devices.  Some at jolla are looking at it, but I dont know the priority on it. cc @abranson

**Comment by tiocfaidharla** [comment]
I did the Vconn tweak on my BH, double tap still wakes up.

**Comment by bam80** [comment]
Could you guys elaborate a bit more on where the double touch to wake feature is implemented?
I'm new PinePhone user/dev and need help on this. Currently, it doesn't work for me on Manjaro Plasma, despite others "success stories".. 

I can't get how it can even work as the touch driver doesn't seem to issue any I2C commands to enter Gesture mode:
https://github.com/torvalds/linux/blob/master/drivers/input/touchscreen/goodix.c

**Comment by carlosgonz0** [comment]
> Could you guys elaborate a bit more on where the double touch to wake feature is implemented? I'm new PinePhone user/dev and need help on this. Currently, it doesn't work for me on Manjaro Plasma, despite others "success stories"..
> 
> I can't get how it can even work as the touch driver doesn't seem to issue any I2C commands to enter Gesture mode: https://github.com/torvalds/linux/blob/master/drivers/input/touchscreen/goodix.c

Pinephone already support double touch to wake under Sailfish. Some time the double touch to wake not worked on Pinephone brave edition, so i upgraded the brave edition board to Beta edition and double touch to wake work just fine.

**Comment by bam80** [comment]
@carlosgonz0 thanks but it still doesn't explain how it's possible.
Does Sailfish use different driver?
