### ISSUE TITLE
PinePhone CE BH needed to port.

### ISSUE THREAD

**Issue by GNUuser** [sailfish-on-dontbeevil/droid-config-pinephone#49]
I just want to know if YOU have the PinePhone CE or BH to port SF as well, if  missing, to get one for you.
Thanks of advance

**Comment by DylanVanAssche** [comment]
I have ordered the pmOS CE 3GB RAM version. Should be shipping by the end of this month

**Comment by GNUuser** [comment]
> I have ordered the pmOS CE 3GB RAM version. Should be shipping by the end of this month

OK. I will order one pmOS CE 3GB RAM version too. So @piggz @neochapay  have a BH,CE,PMOS device to development?

**Comment by piggz** [comment]
Dont stress too much, i think im getting sent a 3gb main board so I should be ok.

**Comment by GNUuser** [comment]
> Dont stress too much, i think im getting sent a 3gb main board so I should be ok.

 3gb-main-board  it is expected that it will be available by the year 2021, So I don't want to waste more time than was already lost.

I will buy you a shiny brand new PinePhone Posmarket edition 3GB +  silicone case.
Text me your Address to carlosgonz@protonmail.com or tell me a paypal account.

**Comment by piggz** [comment]
I think it would be better to go to @neochapay as he has done the most technical aspects of the port, camera and ofono, which was a bit out of me comfort zone, and he is best place to utilise the new board to get hdmi output.

**Comment by GNUuser** [comment]
> I think it would be better to go to @neochapay ....

Yeah I know that  @neochapay need a device too.

But let me start with you first @piggz . I am on the telegram-channel: sailfish_es then yesterday i said on the group that you @piggz needed  a PinePhone to port better Sailfish, so all the people on the group in sailfish_es  they said they are happy to collaborate to buy you the pinephone, so the money was collected in less than 5 minutes to order the pinephone-3GBs to you. @pigg the group  sailfish_es is appreciate you very much for your good work to SF.

**Comment by piggz** [comment]
Ok, if youre going to insist then fair enough, however, i will have to insist that if my main board arrives, then I will send the device to @neochapay if he doesnt have one yet, as he's doing loads for sailfish and nemo atm.

**Comment by GNUuser** [comment]
> Ok, if youre going to insist then fair enough, however, i will have to insist that if my main board arrives, then I will send the device to @neochapay if he doesnt have one yet, as he's doing loads for sailfish and nemo atm.

OK send me your address to my email. It only 8 day left to order a pinephone please.

**Comment by GNUuser** [comment]
@neochapay Where are you why don't you show up here?

**Comment by neochapay** [comment]
I always here. But i hard work about cameras on pp and nemo. If you want send me pniephone it will be good bwcause Tl Lim cant send me new versions of hardware because not yet resume post service to Russia

**Comment by GNUuser** [comment]
Thank you @neochapay for you hard work to PinePhone, please fix volumen buttom too. : )
But if Rusia Post is not in service I can not sean a PP too.

**Comment by GNUuser** [comment]
@piggz In your country postal service is working well to send the PP??

**Comment by piggz** [comment]
Yes, DHL or regular post works fine here :)

**Comment by GNUuser** [comment]
> Yes, DHL or regular post works fine here :)

OK.

**Comment by neochapay** [comment]
Yea...volume button...i forgot about it...

**Comment by neochapay** [comment]
> Thank you @neochapay for you hard work to PinePhone, please fix volumen buttom too. : )
> But if Rusia Post is not in service I can not sent a PP too.

https://www.youtube.com/watch?v=9NGp5VRbWLc volume button work fine

**Comment by GNUuser** [comment]
> https://www.youtube.com/watch?v=9NGp5VRbWLc volume button work fine

Volumen control tot work to me, volumen gui work but not control the sound always the speaker is in high level. PP BH

**Comment by GNUuser** [comment]
*2265100 DONE.
