### ISSUE TITLE
Call bugs

### ISSUE THREAD

**Issue by tiocfaidharla** [sailfish-on-dontbeevil/droid-config-pinephone#51]
Contacts that have an international code +XXX but are local to me do not connect. I get a recording saying the number is incorrect. Foreign numbers get the same message.
If I dial a number and try to 'cancel' the call before it answers it continues anyway. The 'end call' button works correctly.

**Comment by tiocfaidharla** [comment]
update: made a local call, I could hear fine, the other person heard nothing at all

**Comment by piggz** [comment]
Could you please give feedback with the latest image from today.  I have made many changes to ofono and am getting mixed results.  Please confirm behaviour of
Outgoing Call
Incoming call from screen-on state
Incoming call from sleep state
Ability to end call from incoming
Ability to end call from outgoing
Ofono version (rpm -qi ofono)
SailfishOS version
Modem firmware version (eg stock or flashed)
Stability after sever hours
Any other notes

**Comment by piggz** [comment]
I believe this is resolved, if not, please re-open
