### ISSUE TITLE
SSH not connecting 

### ISSUE THREAD

**Issue by andybleaden** [sailfish-on-dontbeevil/droid-config-pinephone#60]
Attempt to connect to pinephone via SSH via ssh defaultuser@192.168.2.15
Expected to be connected and request for password
Connection never happens and times out

**Comment by piggz** [comment]
This should work.  it doesnt work if the cable is plugged in while the phone boots, you have to un/plut it to start ssh.  Please confirm.

**Comment by andybleaden** [comment]
Had a spare mo and retried this. Recognises a plug in- switches to charging mode despite me selecting developer mode - ran ssh defaultuser@192.168.2.15 and got no response at all. 

Strange one 
Also not seeing MTP functioning but that was the case for other oneplus phones I had used on sailfish.

**Comment by piggz** [comment]
This is currently fixed and I am using it regularly
